"use client";

import { motion } from "framer-motion";

const features = [
  {
    icon: "🎯",
    title: "Creator Blueprint",
    description:
      "Answer a few questions and get a personalized niche, content strategy, brand voice, and 90-day growth roadmap — generated by AI.",
  },
  {
    icon: "🔍",
    title: "SEO Research Center",
    description:
      "Find high-opportunity keywords, analyze search intent, discover long-tail topics, and generate optimized titles, descriptions, and tags.",
  },
  {
    icon: "🤖",
    title: "AI Content Studio",
    description:
      "Generate hooks, full scripts, chapters, community posts, Shorts ideas, and repurposed content for X and LinkedIn — all from one idea.",
  },
  {
    icon: "🖼️",
    title: "Thumbnail Engine",
    description:
      "Get detailed thumbnail concepts with composition, colors, emotions, and text placement — designed to maximize click-through rate.",
  },
  {
    icon: "🕵️",
    title: "Competitor Analyzer",
    description:
      "Reverse-engineer what's working for any channel. Identify their strategy, weaknesses, and exactly how to outperform them.",
  },
  {
    icon: "📋",
    title: "Project Workspace",
    description:
      "Every video gets its own project. Track it from idea to published. Regenerate any section. Never lose your work.",
  },
  {
    icon: "🧠",
    title: "Creator Memory",
    description:
      "CaseTube remembers your brand voice, audience, goals, and style. Every AI output gets smarter and more personalized over time.",
  },
  {
    icon: "📈",
    title: "Retention Engine",
    description:
      "Paste your script and get drop-off risk analysis, pattern interrupt suggestions, and engagement improvements — before you film.",
  },
  {
    icon: "📊",
    title: "Analytics (Coming Soon)",
    description:
      "Connect your YouTube channel and get AI-powered performance explanations in plain English. No spreadsheets needed.",
  },
];

export function Features() {
  return (
    <section id="features" className="py-24 px-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <p className="text-red-500 text-sm font-semibold uppercase tracking-widest mb-3">
            Everything You Need
          </p>
          <h2 className="text-4xl md:text-5xl font-bold text-white">
            Your entire YouTube team.
            <br />
            <span className="text-zinc-500">Powered by AI.</span>
          </h2>
          <p className="mt-4 text-zinc-400 max-w-xl mx-auto">
            Stop juggling 10 different tools. CaseTube is the only platform built
            specifically for YouTube creators who want to grow faster and smarter.
          </p>
        </motion.div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.07, duration: 0.5 }}
              className="group bg-zinc-900/50 border border-zinc-800 hover:border-zinc-600 rounded-2xl p-6 transition-all hover:bg-zinc-900"
            >
              <div className="text-3xl mb-4">{feature.icon}</div>
              <h3 className="text-white font-semibold text-lg mb-2">
                {feature.title}
              </h3>
              <p className="text-zinc-400 text-sm leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
