"use client";

import { motion } from "framer-motion";

const FEATURES = [
  {
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 11a9 9 0 019 9"/><path d="M4 4a16 16 0 0116 16"/><circle cx="5" cy="19" r="1"/>
      </svg>
    ),
    label: "DAILY BRIEFING",
    title: "Personalised Feed",
    description: "Every time you open CaseTube, your feed refreshes with what's trending in your niche, keyword opportunities, title upgrades, milestone progress, and fresh AI-generated content ideas — all backed by live YouTube data.",
    accent: "from-indigo-500/10 to-indigo-500/0",
    border: "hover:border-indigo-500/40",
    labelColor: "text-indigo-400",
    preview: (
      <div className="space-y-2 mt-4">
        {["🔥 Niche Outliers — 3 viral videos in your niche this week", "📈 Keyword: 'AI tools 2025' — Score 91 · Rising", "✨ Title Upgrade — Optimised version ready to copy"].map((item, i) => (
          <div key={i} className="flex items-center gap-2.5 bg-zinc-800/60 rounded-lg px-3 py-2">
            <span className="text-xs text-zinc-300">{item}</span>
          </div>
        ))}
      </div>
    ),
  },
  {
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <polygon points="1 6 1 22 8 18 16 22 23 18 23 2 16 6 8 2 1 6"/><line x1="8" y1="2" x2="8" y2="18"/><line x1="16" y1="6" x2="16" y2="22"/>
      </svg>
    ),
    label: "AI STRATEGY",
    title: "Creator Blueprint",
    description: "Answer a few questions. Get a complete YouTube strategy — your niche, target audience, content pillars, brand voice, posting schedule, monetization plan, and a 90-day growth roadmap. All generated by AI in under 60 seconds.",
    accent: "from-red-500/10 to-red-500/0",
    border: "hover:border-red-500/40",
    labelColor: "text-red-400",
    preview: (
      <div className="mt-4 space-y-2">
        {[
          { label: "Your Niche", value: "EdTech & AI Tools" },
          { label: "Target Audience", value: "Students 18–35, US/UK" },
          { label: "Posting Schedule", value: "2× per week, Tue & Thu" },
        ].map((item) => (
          <div key={item.label} className="flex justify-between items-center bg-zinc-800/60 rounded-lg px-3 py-2">
            <span className="text-zinc-500 text-xs">{item.label}</span>
            <span className="text-white text-xs font-medium">{item.value}</span>
          </div>
        ))}
      </div>
    ),
  },
  {
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/>
      </svg>
    ),
    label: "REAL YOUTUBE DATA",
    title: "SEO Research Center",
    description: "Keyword research powered by real YouTube data — not guesses. See what's actually ranking, generating clicks, and driving views in your niche right now. Get optimised titles, descriptions, and tags generated from top-performing videos.",
    accent: "from-blue-500/10 to-blue-500/0",
    border: "hover:border-blue-500/40",
    labelColor: "text-blue-400",
    preview: (
      <div className="mt-4 space-y-2">
        {[
          { kw: "ai tools for students", score: 94, diff: "Easy" },
          { kw: "best ai productivity apps", score: 87, diff: "Medium" },
          { kw: "chatgpt tutorial 2025", score: 79, diff: "Medium" },
        ].map((k) => (
          <div key={k.kw} className="flex items-center gap-2 bg-zinc-800/60 rounded-lg px-3 py-2">
            <div className="flex-1 h-1.5 bg-zinc-700 rounded-full overflow-hidden">
              <div className="h-full bg-blue-500 rounded-full" style={{ width: `${k.score}%` }} />
            </div>
            <span className="text-white text-xs font-bold w-7">{k.score}</span>
            <span className="text-zinc-400 text-xs w-14 text-right">{k.diff}</span>
          </div>
        ))}
      </div>
    ),
  },
  {
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 013 3L7 19l-4 1 1-4L16.5 3.5z"/>
      </svg>
    ),
    label: "AI CONTENT",
    title: "Content Studio",
    description: "From one video idea, generate everything — attention-grabbing hooks, full word-for-word scripts, YouTube Shorts, X threads, LinkedIn posts, and email subject lines. Every output is grounded in what's working in your niche right now.",
    accent: "from-purple-500/10 to-purple-500/0",
    border: "hover:border-purple-500/40",
    labelColor: "text-purple-400",
    preview: (
      <div className="mt-4">
        <div className="bg-zinc-800/60 rounded-lg p-3 space-y-2">
          <div className="flex gap-2 mb-2">
            {["Ideas", "Hooks", "Script", "Repurpose"].map((t) => (
              <span key={t} className={`text-xs px-2 py-0.5 rounded-md ${t === "Script" ? "bg-purple-600 text-white" : "bg-zinc-700 text-zinc-400"}`}>{t}</span>
            ))}
          </div>
          <p className="text-zinc-300 text-xs leading-relaxed">"Most people think learning AI tools takes months. They're wrong — and in the next 8 minutes I'll show you exactly why..."</p>
          <div className="flex gap-2 text-xs text-zinc-500 mt-1">
            <span>Hook · 45s</span><span>·</span><span>1,240 words</span>
          </div>
        </div>
      </div>
    ),
  },
  {
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/>
      </svg>
    ),
    label: "LIVE DATA",
    title: "Trend Finder",
    description: "See what's going viral in your niche before everyone else does. Real-time velocity scores show which videos are exploding right now. One click turns any trend into a new video project with full AI content generation.",
    accent: "from-orange-500/10 to-orange-500/0",
    border: "hover:border-orange-500/40",
    labelColor: "text-orange-400",
    preview: (
      <div className="mt-4 space-y-2">
        {[
          { label: "🔥 Viral", title: "I Used Claude AI for 30 Days...", views: "2.4M views · 3d ago" },
          { label: "⚡ Trending", title: "The Best AI Workflow in 2025", views: "847K views · 5d ago" },
        ].map((v, i) => (
          <div key={i} className="bg-zinc-800/60 rounded-lg px-3 py-2">
            <div className="flex items-center gap-2 mb-0.5">
              <span className="text-xs bg-zinc-700 text-zinc-300 px-1.5 py-0.5 rounded">{v.label}</span>
            </div>
            <p className="text-white text-xs font-medium truncate">{v.title}</p>
            <p className="text-zinc-500 text-xs">{v.views}</p>
          </div>
        ))}
      </div>
    ),
  },
  {
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87"/><path d="M16 3.13a4 4 0 010 7.75"/>
      </svg>
    ),
    label: "COMPETITOR INTEL",
    title: "Competitor Analyzer",
    description: "Search any YouTube channel by name, handle, or URL. Instantly see their top keywords, best-performing formats, average views, and biggest content gaps. Know exactly what to make to outrank them.",
    accent: "from-cyan-500/10 to-cyan-500/0",
    border: "hover:border-cyan-500/40",
    labelColor: "text-cyan-400",
    preview: (
      <div className="mt-4 space-y-2">
        <div className="bg-zinc-800/60 rounded-lg px-3 py-2.5">
          <p className="text-white text-xs font-semibold mb-2">@mkbhd · 18.9M subscribers</p>
          <div className="grid grid-cols-2 gap-1.5">
            {[["Avg Views", "2.1M"], ["Top Format", "Reviews"], ["Keywords", "tech, apple, iphone"], ["Gap", "AI tools coverage"]].map(([l, v]) => (
              <div key={l}>
                <p className="text-zinc-500 text-xs">{l}</p>
                <p className="text-white text-xs font-medium truncate">{v}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    ),
  },
  {
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <rect x="2" y="4" width="20" height="16" rx="2"/><circle cx="8.5" cy="10.5" r="1.5"/><polyline points="21 15 16 10 5 21"/>
      </svg>
    ),
    label: "DESIGN TOOL",
    title: "Thumbnail Maker",
    description: "A real canvas-based thumbnail editor — right inside CaseTube. Choose from 6 proven templates, upload your photo, edit text, adjust colors, and export a crisp 1280×720 PNG ready to upload to YouTube.",
    accent: "from-pink-500/10 to-pink-500/0",
    border: "hover:border-pink-500/40",
    labelColor: "text-pink-400",
    preview: (
      <div className="mt-4">
        <div className="bg-zinc-800/60 rounded-lg p-3">
          <div className="flex gap-2 mb-2.5">
            {["Bold Impact", "Face + Text", "Neon Dark", "Split"].map((t, i) => (
              <span key={t} className={`text-xs px-1.5 py-0.5 rounded ${i === 0 ? "bg-pink-600 text-white" : "bg-zinc-700 text-zinc-400"}`}>{t}</span>
            ))}
          </div>
          <div className="w-full h-16 rounded-lg bg-gradient-to-r from-zinc-900 to-zinc-800 border border-zinc-700 flex items-center justify-center">
            <span className="text-white text-sm font-black tracking-tight">YOUR TITLE HERE</span>
          </div>
          <div className="flex justify-end mt-2">
            <span className="text-xs text-pink-400 font-medium">Export 1280×720 PNG →</span>
          </div>
        </div>
      </div>
    ),
  },
  {
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z"/>
      </svg>
    ),
    label: "VIDEO WORKFLOW",
    title: "Project Workspace",
    description: "Every video gets its own dedicated workspace. Move through 7 stages — Research, Planning, Writing, Thumbnail, Editing, Publishing, Analysis. Generate AI content at each stage. Never lose your work or start from scratch.",
    accent: "from-green-500/10 to-green-500/0",
    border: "hover:border-green-500/40",
    labelColor: "text-green-400",
    preview: (
      <div className="mt-4">
        <div className="bg-zinc-800/60 rounded-lg p-3">
          <p className="text-white text-xs font-semibold mb-2.5 truncate">How to Use AI Tools in 2025</p>
          <div className="flex gap-1 mb-2">
            {["Research", "Planning", "Writing", "Thumbnail", "Editing", "Publishing", "Analysis"].map((s, i) => (
              <div key={s} className={`h-1.5 flex-1 rounded-full ${i <= 2 ? "bg-green-500" : "bg-zinc-700"}`} />
            ))}
          </div>
          <div className="flex justify-between text-xs text-zinc-500">
            <span>Stage 3 of 7 · Writing</span>
            <span>6 sections generated</span>
          </div>
        </div>
      </div>
    ),
  },
];

export function Features() {
  return (
    <section id="features" className="py-24 px-6">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <p className="text-red-500 text-xs font-bold uppercase tracking-widest mb-4">
            Everything You Need to Grow on YouTube
          </p>
          <h2 className="text-4xl md:text-5xl font-bold text-white leading-tight">
            Your entire YouTube team.
            <br />
            <span className="text-zinc-500">Powered by AI.</span>
          </h2>
          <p className="mt-5 text-zinc-400 max-w-lg mx-auto text-sm leading-relaxed">
            Stop juggling 10 different tools. CaseTube is the only platform built
            specifically for YouTube creators who want to grow faster and smarter.
          </p>
        </motion.div>

        {/* 2-column grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {FEATURES.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.06, duration: 0.5 }}
              className={`group relative bg-gradient-to-b ${f.accent} border border-zinc-800 ${f.border} rounded-2xl p-6 transition-all duration-300 hover:bg-zinc-900/60 overflow-hidden`}
            >
              {/* Top row */}
              <div className="flex items-start justify-between mb-4">
                <div className={`${f.labelColor} opacity-80`}>{f.icon}</div>
                <span className={`text-xs font-bold tracking-widest ${f.labelColor} opacity-60`}>{f.label}</span>
              </div>

              {/* Title + description */}
              <h3 className="text-white font-bold text-xl mb-2">{f.title}</h3>
              <p className="text-zinc-400 text-sm leading-relaxed">{f.description}</p>

              {/* Preview */}
              {f.preview}
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
